# Generated by Django 5.0.3 on 2024-03-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(default=1, upload_to='blogs'),
            preserve_default=False,
        ),
    ]
